env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier/@typescript-eslint
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - prettier
  - react
  - react-hooks
  - "@typescript-eslint"
rules: {}
