version: '3.9'

services:
  client:
    build:
      context: ./Client
      dockerfile: ./build/dev/Dockerfile
    volumes:
      - ./Client:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
    ports:
      - "53000:3000"
    stdin_open: true 
  server:
    build: 
      context: ./Server
      dockerfile: ./build/Dockerfile
    volumes:
      - ./Server:/go/src/app
    ports:
      - "58080:8080"
    restart: always
    environment: 
      - MYSQL_HOST=${MYSQL_HOST}
    # depends_on:
    #   - db
volumes:
  node_modules_volume: