version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: ./Client/build/Dockerfile
    volumes:
      - ./Client:/usr/src/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
    ports:
      - "53000:3000"
    stdin_open: true 