version: "3.9"

services:
  client:
    build:
      context: ./Client
      dockerfile: ./build/dev/Dockerfile
    volumes:
      - ./Client:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
    ports:
      - "53000:3000"
    networks:
      - otasuke_app_network
    stdin_open: true
  server:
    build:
      context: ./Server
      dockerfile: ./build/Dockerfile
    volumes:
      - ./Server:/go/src/app
    environment:
      - APP_ENV=dev
    ports:
      - "58080:8080"
    networks:
      - otasuke_app_network
    restart: always
    depends_on:
      - db
  db:
    image: mysql:8.0.36
    container_name: "dockerMySQL"
    volumes:
      - ./Server/db/my.cnf:/etc/mysql/conf.d/my.cnf
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_DATABASE=react_go_otasuke_db
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    networks:
      - otasuke_app_network
volumes:
  node_modules_volume:
networks:
  otasuke_app_network:
    external: true
